{% extends 'layout.phtml' %}

{% block content %}
<section class="col-md-5 col-md-offset-4">
  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      {% for i in 0..(raws|length - 1) %}
      <li data-target="#carousel-example-generic" data-slide-to="{{ i }}"{% if loop.first %} class="active"{% endif %}></li>
      {% endfor %}
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      {% for raw in  raws %}
      <div class="item{% if loop.first %} active{% endif %}">
        <img src="{{ raw.url }}" width="{{ raw.width / 2}}">
        <div class="carousel-caption">
          <a href="/hw3/?imgid={{ raw.id }}" target="_blank" class="btn btn-default">see original image</a>
        </div>
      </div>
      {% endfor %}
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</section>
{% endblock %}
