<!doctype html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" crossorigin="anonymous">
  <title>Простая галерея</title>
</head>
<body class="container">
  <header>
    <h1>{{ header }}</h1>
  </header>
  <div class="row">
    {% block content %}{% endblock %}
  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.min.js"crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" crossorigin="anonymous"></script>
</body>
</html>
